import { AdminShell } from "@/components/admin/admin-shell";
import { requireOrderAdmin } from "@/lib/admin-auth";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";

export default async function AdminCustomersPage() {
  await requireOrderAdmin();
  const { data } = await createSupabaseAdminClient().from("customer_profiles").select("user_id,email,first_name,last_name,birthday_month,birthday_day,created_at,loyalty_accounts(currency,progress_minor,lifetime_eligible_minor,rewards_issued)").order("created_at", { ascending: false }).limit(200);
  return <AdminShell><main className="mx-auto max-w-page px-5 py-10"><p className="font-redhat text-sm font-semibold uppercase text-ruby">AMARÉE Club</p><h1 className="mt-3 font-newsreader text-5xl">Zákazníci</h1><p className="mt-4 font-redhat text-sm text-muted">Přehled účtů a započítaných nákupů. Marketingový souhlas se eviduje samostatně.</p><div className="mt-8 overflow-x-auto border border-line bg-white"><table className="w-full min-w-[860px] border-collapse text-left font-redhat text-sm"><thead><tr className="border-b border-line text-xs uppercase text-muted"><th className="px-5 py-4">Zákazník</th><th className="px-5 py-4">E-mail</th><th className="px-5 py-4">Narozeniny</th><th className="px-5 py-4">Průběh CZK</th><th className="px-5 py-4">Průběh EUR</th><th className="px-5 py-4">Odměny</th></tr></thead><tbody>{(data ?? []).map((customer) => { const accounts = customer.loyalty_accounts as unknown as Array<{ currency: string; progress_minor: number; rewards_issued: number }>; const czk = accounts.find((item) => item.currency === "CZK"); const eur = accounts.find((item) => item.currency === "EUR"); return <tr className="border-b border-line last:border-0" key={customer.user_id}><td className="px-5 py-4 font-semibold">{[customer.first_name, customer.last_name].filter(Boolean).join(" ") || "—"}</td><td className="px-5 py-4">{customer.email}</td><td className="px-5 py-4">{customer.birthday_day && customer.birthday_month ? `${customer.birthday_day}. ${customer.birthday_month}.` : "—"}</td><td className="px-5 py-4">{new Intl.NumberFormat("cs-CZ", { style: "currency", currency: "CZK" }).format((czk?.progress_minor ?? 0) / 100)}</td><td className="px-5 py-4">{new Intl.NumberFormat("sk-SK", { style: "currency", currency: "EUR" }).format((eur?.progress_minor ?? 0) / 100)}</td><td className="px-5 py-4">{(czk?.rewards_issued ?? 0) + (eur?.rewards_issued ?? 0)}</td></tr>; })}</tbody></table>{!data?.length ? <p className="p-6 font-redhat text-sm text-muted">Zatím nebyl vytvořen žádný zákaznický účet.</p> : null}</div></main></AdminShell>;
}
