-- Intentionally empty.
-- The development baseline creates required categories, shipping options and
-- payment options. Products and discount codes must be created through /admin
-- so staging exercises the same workflow as production.
