// @ts-expect-error Generated by `npm run cf:build` before Wrangler bundles this entrypoint.
import nextHandler from "./.open-next/worker.js";

type WorkerEnvironment = {
  APP_ENV?: string;
  NEXT_PUBLIC_SUPABASE_URL?: string;
  SUPABASE_SERVICE_ROLE_KEY?: string;
};

type WorkerExecutionContext = {
  waitUntil(promise: Promise<unknown>): void;
};

async function expireReservations(env: WorkerEnvironment) {
  if (!env.NEXT_PUBLIC_SUPABASE_URL || !env.SUPABASE_SERVICE_ROLE_KEY) {
    throw new Error("supabase_cron_configuration_missing");
  }

  const response = await fetch(`${env.NEXT_PUBLIC_SUPABASE_URL}/rest/v1/rpc/expire_due_stock_reservations`, {
    method: "POST",
    headers: {
      apikey: env.SUPABASE_SERVICE_ROLE_KEY,
      Authorization: `Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`,
      "Content-Type": "application/json"
    },
    body: JSON.stringify({ p_limit: 100 })
  });

  if (!response.ok) throw new Error(`reservation_expiry_failed_${response.status}`);
}

const worker = {
  fetch: nextHandler.fetch,
  scheduled(_event: unknown, env: WorkerEnvironment, ctx: WorkerExecutionContext) {
    ctx.waitUntil(expireReservations(env));
  }
};

export default worker;
