begin;

do $$
begin
  create type public.product_publication_status as enum ('draft', 'active', 'hidden', 'archived');
exception
  when duplicate_object then null;
end
$$;

alter table public.products
  add column if not exists publication_status public.product_publication_status;

update public.products
set publication_status = case
  when archived_at is not null then 'archived'::public.product_publication_status
  when active then 'active'::public.product_publication_status
  else 'draft'::public.product_publication_status
end
where publication_status is null;

alter table public.products
  alter column publication_status set default 'draft',
  alter column publication_status set not null,
  alter column internal_id set default (gen_random_uuid()::text);

create index if not exists products_publication_status_idx
  on public.products(publication_status, sort_order, updated_at desc);

comment on column public.products.id is 'Database-generated immutable technical product identifier exposed read-only in admin.';
comment on column public.products.internal_id is 'Legacy immutable compatibility identifier generated by PostgreSQL; never edited in admin.';
comment on column public.products.publication_status is 'Editorial lifecycle: draft, active, hidden or archived. Only active is public.';

create or replace function public.admin_product_publish_issues(p_product_id uuid)
returns text[]
language plpgsql
stable
security definer
set search_path = public, auth
as $$
declare
  issues text[] := array[]::text[];
begin
  if not public.is_admin_user() then
    raise exception 'admin_required' using errcode = '42501';
  end if;
  if not exists (select 1 from public.products where id = p_product_id) then
    raise exception 'product_not_found';
  end if;

  if not exists (
    select 1 from public.product_translations
    where product_id = p_product_id and locale = 'cs' and length(trim(name)) >= 2
  ) then issues := array_append(issues, 'name'); end if;

  if not exists (
    select 1 from public.product_translations
    where product_id = p_product_id and locale = 'cs' and slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'
  ) then issues := array_append(issues, 'slug'); end if;

  if not exists (
    select 1 from public.product_prices
    where product_id = p_product_id and currency = 'CZK' and amount_minor > 0
  ) then issues := array_append(issues, 'price'); end if;

  if not exists (
    select 1 from public.inventory_items
    where product_id = p_product_id and variant_id is null and quantity >= 0
  ) then issues := array_append(issues, 'inventory'); end if;

  if not exists (
    select 1 from public.product_images
    where product_id = p_product_id and is_primary and archived_at is null
  ) then issues := array_append(issues, 'primary_image'); end if;

  return issues;
end;
$$;

revoke all on function public.admin_product_publish_issues(uuid) from public;
grant execute on function public.admin_product_publish_issues(uuid) to authenticated;

create or replace function public.admin_upsert_product(p_product_id uuid, p_payload jsonb)
returns uuid
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  target_product_id uuid := coalesce(p_product_id, gen_random_uuid());
  target_category_id uuid;
  target_status public.product_publication_status := coalesce(p_payload->>'publicationStatus', 'draft')::public.product_publication_status;
  selected_locale text;
  translation jsonb;
  selected_currency text;
  price_data jsonb;
  publish_issues text[];
begin
  if not public.is_admin_user() then
    raise exception 'admin_required' using errcode = '42501';
  end if;

  select id into target_category_id
  from public.categories
  where internal_slug = p_payload->>'category' and active;
  if target_category_id is null then raise exception 'category_not_found'; end if;

  insert into public.products(
    id, sku, category_id, weight_grams, active, publication_status, featured, is_new,
    sort_order, low_stock_threshold, archived_at
  ) values (
    target_product_id,
    upper(p_payload->>'sku'),
    target_category_id,
    nullif(p_payload->>'weightGrams', '')::numeric,
    false,
    'draft',
    coalesce((p_payload->>'featured')::boolean, false),
    coalesce((p_payload->>'isNew')::boolean, false),
    coalesce((p_payload->>'sortOrder')::integer, 0),
    coalesce((p_payload->>'lowStockThreshold')::integer, 2),
    null
  )
  on conflict (id) do update set
    sku = excluded.sku,
    category_id = excluded.category_id,
    weight_grams = excluded.weight_grams,
    active = false,
    publication_status = 'draft',
    featured = excluded.featured,
    is_new = excluded.is_new,
    sort_order = excluded.sort_order,
    low_stock_threshold = excluded.low_stock_threshold,
    archived_at = null;

  foreach selected_locale in array array['cs', 'en', 'de'] loop
    translation := p_payload->'translations'->selected_locale;
    insert into public.product_translations(
      product_id, locale, slug, name, short_description, long_description,
      material, color, dimensions, care, seo_title, seo_description
    ) values (
      target_product_id, selected_locale, translation->>'slug', translation->>'name',
      translation->>'shortDescription', translation->>'longDescription',
      translation->>'material', translation->>'color', translation->>'dimensions',
      translation->>'care', translation->>'seoTitle', translation->>'seoDescription'
    )
    on conflict (product_id, locale) do update set
      slug = excluded.slug,
      name = excluded.name,
      short_description = excluded.short_description,
      long_description = excluded.long_description,
      material = excluded.material,
      color = excluded.color,
      dimensions = excluded.dimensions,
      care = excluded.care,
      seo_title = excluded.seo_title,
      seo_description = excluded.seo_description;
  end loop;

  foreach selected_currency in array array['CZK', 'EUR'] loop
    price_data := p_payload->'prices'->selected_currency;
    insert into public.product_prices(product_id, currency, amount_minor, original_amount_minor)
    values (
      target_product_id,
      selected_currency,
      (price_data->>'amountMinor')::integer,
      nullif(price_data->>'originalAmountMinor', '')::integer
    )
    on conflict (product_id, currency) do update set
      amount_minor = excluded.amount_minor,
      original_amount_minor = excluded.original_amount_minor;
  end loop;

  insert into public.inventory_items(product_id, variant_id, quantity)
  values (target_product_id, null, (p_payload->>'stockQuantity')::integer)
  on conflict (product_id) where variant_id is null do update set quantity = excluded.quantity;

  if target_status = 'active' then
    publish_issues := public.admin_product_publish_issues(target_product_id);
    if cardinality(publish_issues) > 0 then
      raise exception 'product_publish_incomplete:%', array_to_string(publish_issues, ',');
    end if;
  end if;

  update public.products
  set publication_status = target_status,
      active = target_status = 'active',
      archived_at = case when target_status = 'archived' then coalesce(archived_at, now()) else null end
  where id = target_product_id;

  return target_product_id;
end;
$$;

revoke all on function public.admin_upsert_product(uuid, jsonb) from public;
grant execute on function public.admin_upsert_product(uuid, jsonb) to authenticated;

create or replace function public.admin_set_product_status(
  p_product_id uuid,
  p_status public.product_publication_status
)
returns text[]
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  issues text[] := array[]::text[];
begin
  if not public.is_admin_user() then raise exception 'admin_required' using errcode = '42501'; end if;
  if not exists (select 1 from public.products where id = p_product_id) then raise exception 'product_not_found'; end if;

  if p_status = 'active' then
    issues := public.admin_product_publish_issues(p_product_id);
    if cardinality(issues) > 0 then return issues; end if;
  end if;

  update public.products
  set publication_status = p_status,
      active = p_status = 'active',
      archived_at = case when p_status = 'archived' then coalesce(archived_at, now()) else null end
  where id = p_product_id;
  return issues;
end;
$$;

revoke all on function public.admin_set_product_status(uuid, public.product_publication_status) from public;
grant execute on function public.admin_set_product_status(uuid, public.product_publication_status) to authenticated;

create or replace function public.admin_set_product_active(p_product_id uuid, p_active boolean)
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  issues text[];
begin
  issues := public.admin_set_product_status(
    p_product_id,
    case when p_active then 'active'::public.product_publication_status else 'draft'::public.product_publication_status end
  );
  if cardinality(issues) > 0 then
    raise exception 'product_publish_incomplete:%', array_to_string(issues, ',');
  end if;
end;
$$;

drop policy if exists public_products_read on public.products;
create policy public_products_read on public.products for select using (
  publication_status = 'active' and active and archived_at is null
);

drop policy if exists public_product_translations_read on public.product_translations;
create policy public_product_translations_read on public.product_translations for select using (
  exists (select 1 from public.products p where p.id = product_id and p.publication_status = 'active' and p.active and p.archived_at is null)
);

drop policy if exists public_product_prices_read on public.product_prices;
create policy public_product_prices_read on public.product_prices for select using (
  exists (select 1 from public.products p where p.id = product_id and p.publication_status = 'active' and p.active and p.archived_at is null)
);

drop policy if exists public_variants_read on public.product_variants;
create policy public_variants_read on public.product_variants for select using (
  active and archived_at is null and exists (
    select 1 from public.products p where p.id = product_id and p.publication_status = 'active' and p.active and p.archived_at is null
  )
);

drop policy if exists public_inventory_read on public.inventory_items;
create policy public_inventory_read on public.inventory_items for select using (
  exists (select 1 from public.products p where p.id = product_id and p.publication_status = 'active' and p.active and p.archived_at is null)
);

drop policy if exists public_product_images_read on public.product_images;
create policy public_product_images_read on public.product_images for select using (
  archived_at is null and exists (
    select 1 from public.products p where p.id = product_id and p.publication_status = 'active' and p.active and p.archived_at is null
  )
);

commit;
